import { Inter } from "next/font/google";
import "./globals.css";
import NavbarComponent from "./components/NavbarComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Legend Cinama",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={inter.className}>
        <NavbarComponent/>
        {children}
      </body>
    </html>
  );
}
